### ISSUE TITLE
correct the build and mark as broken!

### ISSUE THREAD

**Issue by ngam** [conda-forge/libtvm-feedstock#25]
This is incomplete. Please see the docs about `__osx` run requirement. You'll have to mark this build as broken after you have fixed it.

_Originally posted by @isuruf in https://github.com/conda-forge/libtvm-feedstock/pull/23#discussion_r825580493_

**Comment by ngam** [comment]
> This is incomplete. Please see the docs about `__osx` run requirement. You'll have to mark this build as broken after you have fixed it.

I saw that part of the documentation and my reading from it was that the `__osx` part was optional. And it made sense because the error you would get once you install tvm-py and import it is something along the lines of "you need sdk 11.0 or higher". 

```
OSError: dlopen(/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/testtvms/lib/libtvm.dylib, 10): Symbol not found: _BNNSFilterApplyTwoInputBatch
  Referenced from: /Users/ngam/.Mambaforge-MacOSX-x86_64/envs/testtvms/lib/libtvm.dylib (which was built for Mac OS X 11.0)

```

Did I misread this? Should I still include that?

Full error:

```
(testtvms) ngam@mp15:~$ python
Python 3.10.2 | packaged by conda-forge | (main, Mar  8 2022, 16:02:23) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/testtvms/lib/python3.10/site-packages/tvm/__init__.py", line 26, in <module>
    from ._ffi.base import TVMError, __version__, _RUNTIME_ONLY
  File "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/testtvms/lib/python3.10/site-packages/tvm/_ffi/__init__.py", line 28, in <module>
    from .base import register_error
  File "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/testtvms/lib/python3.10/site-packages/tvm/_ffi/base.py", line 71, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/testtvms/lib/python3.10/site-packages/tvm/_ffi/base.py", line 57, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/testtvms/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/testtvms/lib/libtvm.dylib, 10): Symbol not found: _BNNSFilterApplyTwoInputBatch
  Referenced from: /Users/ngam/.Mambaforge-MacOSX-x86_64/envs/testtvms/lib/libtvm.dylib (which was built for Mac OS X 11.0)
  Expected in: /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
 in /Users/ngam/.Mambaforge-MacOSX-x86_64/envs/testtvms/lib/libtvm.dylib

```

```
(testtvms) ngam@mp15:~$ xcrun --show-sdk-version       
10.15.6

```

**Comment by isuruf** [comment]
> I saw that part of the documentation and my reading from it was that the __osx part was optional.

No, it's not.

>  And it made sense because the error you would get once you install tvm-py and import it is something along the lines of "you need sdk 11.0 or higher".

Adding `__osx` would make the solver not install tvm on a macos<11 machine.

**Comment by ngam** [comment]
Alright, will fix. Thanks @isuruf!

**Comment by ngam** [comment]
action plan:
- [ ] test w/o target; 
  - [ ] if works, avoid setting target
  - [ ] if not, set target and and set __osx
- [x] mark previous builds as broken. (Probably should mark all as broken and do fresh builds for all platforms to be safe --- perhaps adding #15 in the mix
- [ ] ~test compiling [mxnet staged-recipes/](https://github.com/conda-forge/staged-recipes/pull/17620) with tvm~ see new issue for this separately
